name = "PlasmaBenchmarks"
uuid = "6b24e08c-5c15-4c9d-ae3e-ae7edda8f8a3"
authors = ["Gabriel Birnbaum <gbbinbum@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Plasma = "d4286570-51d5-4bbe-9c0b-035637fe1a6e"

[compat]
Plasma = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
